commons/types/Availability.d.ts, components/availability/package.json, components/availability/src/Availability.svelte, components/availability/src/index.html
- Knocks a few hundred kb off the component by only importing the d3 modules we're using
- fixes a few type errors / adds an extension to the `Availability.Timeslot` type
=> Type errors fixed and d3 modularized

.github/ISSUE_TEMPLATE/request-for-comment.md
=> Update issue templates

commons/src/types/Availability.ts, components/availability/src/Availability.svelte
Hotfix: correcting a broken typescript import in availability, and getting tsc to a passing state.
=> Fixing typescript and import errors on availability types

components/mailbox/src/Mailbox.svelte, components/mailbox/src/init.spec.js
- added tests for unread/read actions, bulk actions
- added skipped tests for delete actions to be fully implemented when Folders are used in Mailbox
[ch65621]
=> [Mailbox] Tests for actions

README.md
=> Updated README to include instructions about setting up .env file

components/agenda/src/Agenda.svelte, components/composer/src/Composer.svelte, components/contact-list/src/ContactList.svelte, components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte
=> Fixed internal prop builder causing prop bindings to fire when there is no change

commons/src/store/conversations.ts, components/conversation/src/Conversation.svelte, components/conversation/src/index.html, package.json
Back to functional again!
Note:
- still using clean conversations endpoint, so if you don't have it enabled, you may get a console error / default message.body insetad
=> Conversation component now uses component -> store -> connection pattern

components/availability/src/Availability.svelte
=> Nylas Availability: Ensure a minimum tick width

commons/src/types/Events.ts, commons/src/types/ScheduleEditor.ts, commons/src/types/Scheduler.ts, components/availability/src/Availability.svelte, components/availability/src/index.html, components/schedule-editor/src/ScheduleEditor.svelte, components/scheduler/src/Scheduler.svelte, components/scheduler/src/index.html
=> Added event location and conferencing to schedule editor and scheduler

commons/src/types/Nylas.ts, components/email/src/Email.svelte
- Fixed keypress on return to mailbox not working as expected bug
=> [Email]: Fixed keypress on return to mailbox not working as expected bug

components/availability/src/Availability.svelte, components/scheduler/src/Scheduler.svelte, components/scheduler/src/index.html
=> Nylas scheduler: booker design

components/availability/src/Availability.svelte, components/scheduler/src/Scheduler.svelte, components/scheduler/src/index.html
=> Revert "Nylas scheduler: booker design"

components/availability/src/Availability.svelte, components/availability/src/index.html, components/availability/src/init.spec.js, components/scheduler/src/index.html
=> Nylas availability: style changes

commons/src/types/Availability.ts, commons/src/types/ScheduleEditor.ts, components/availability/src/Availability.svelte, components/availability/src/index.html
Simplifies event buffer to happen in a single addition/subtraction from start/end time.
=> Simplified version of buffer

cypress.json
=> Cypress retries for failing tests to become merely flaky

components/agenda/src/index.html
=> added space between label and input field in save event modal

commons/src/types/Availability.ts, commons/src/types/ScheduleEditor.ts, components/availability/src/Availability.svelte, components/schedule-editor/src/ScheduleEditor.svelte
=> [Hotfix] Add null state to `capacity` to fix Scheduler demo

components/agenda/src/Agenda.svelte, components/composer/src/Composer.svelte, components/composer/src/components/AlertBar.svelte, components/composer/src/components/Attachment.svelte, components/composer/src/components/DatepickerModal.svelte, components/composer/src/components/HTMLEditor.svelte, components/composer/src/dark.css, components/contact-list/src/ContactList.svelte, components/contacts-search/src/ContactsSearch.svelte, components/mailbox/src/Mailbox.svelte
This reverts commit bfd4252c6b4db925793166b566ddd47564fa2206.
=> Revert "Fix CSS Vars so overrides work (#164)"

components/conversation/src/Conversation.svelte, components/email/src/Email.svelte
- Updated Conversation component to make use of the ContactImage component `<nylas-contact-image>` 
- Fixed the bug where multiple picture fetches were being made
=> [Conversation]: Refactored to use nylas-contact-image and fixed multiple avatar fetches

components/agenda/src/Agenda.svelte, components/agenda/src/init.spec.js, components/contact-list/src/ContactList.svelte, components/contact-list/src/init.spec.js
Just need to be reactive to custom data :) 
=> Fix custom data handling so toggling between Nylas/Custom works

.github/workflows/build-test-publish.yaml
=> Fixed parallelization

.github/workflows/build-test-publish.yaml, lerna.json, package.json
=> [devops] fix release npm scripts

.github/workflows/build-test-publish.yaml, package.json
=> [devops] fix release scripts

README.md
=> [docs] workaround for nextjs

commons/src/methods/colour.ts, commons/src/methods/component.ts, commons/src/methods/datetime.ts, commons/src/store/availability.ts, commons/src/types/Availability.ts, commons/src/types/Contacts.ts, commons/src/types/Nylas.ts, commons/src/types/Scheduler.ts, components/agenda/src/Agenda.svelte, components/availability/src/Availability.svelte, components/composer/src/Composer.svelte, components/composer/src/init.spec.js, components/contact-list/src/ContactList.svelte, components/conversation/src/Conversation.svelte, components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte, components/schedule-editor/src/ScheduleEditor.svelte, components/schedule-editor/src/styles/schedule-editor.scss, components/scheduler/src/Scheduler.svelte, tests/agenda/agenda.spec.ts
- Replace `internalProps` with `_this`
- Removed component-level property to `interalProps` matching
- Added extra undefined checks since `_this` props aren't loaded until after the first tick
=> Reworked internal component properties to be accessed through internal _this object

commons/src/components/MessageBody.svelte, components/conversation/src/Conversation.svelte, components/email/src/Email.svelte
- Testing to see if changing the import fixes the external dependency issue
=> [Components]: Fix import for dompurify causing external dependency error

components/mailbox/src/Mailbox.svelte
- Fixed properties not being updated correctly once the message fetch request completes.
=> [Mailbox] Fixed displayed message body not being updated once it has been fetched

components/conversation/src/Conversation.svelte
- adds CSS variables for commonly-changeable styles
- Fixes a bug where tablet header was causing unintended horizontal scroll
=> Conversation component: CSS Vars and horizontal overflow fix

components/email/src/Email.svelte, components/email/src/init.spec.js
- Added css vars with defaults for background and color customizations
=> [Email]: CSS variables for background and color customizations

components/email/src/Email.svelte
=> [Email] Remove invalid import

commons/src/components/NError.svelte, commons/src/connections/contacts.ts, commons/src/connections/folders.ts, commons/src/connections/labels.ts, commons/src/store/contact-avatar.ts, commons/src/store/contacts.ts, commons/src/store/folders.ts, commons/src/store/labels.ts, components/contact-list/src/ContactList.svelte
- Removed circular dependencies within the repo. A couple circular dependencies still exist within our d3 imports: 
```
[1] @nylas/components-availability: (!) Circular dependencies
[1] @nylas/components-availability: ../../node_modules/d3-interpolate/src/value.js -> ../../node_modules/d3-interpolate/src/array.js -> ../../node_modules/d3-interpolate/src/value.js
[1] @nylas/components-availability: ../../node_modules/d3-interpolate/src/value.js -> ../../node_modules/d3-interpolate/src/object.js -> ../../node_modules/d3-interpolate/src/value.js
```
=> Removed circular dependencies throughout the repo

components/schedule-editor/src/index.html, components/scheduler/src/index.html
=> [scheduler] update email_ids to participants on availability

.github/workflows/build-test-publish.yaml
- []
- [] Added changes to component `CHANGELOG.md`
=> Pr hg/auto timebox fix 2

components/composer/CHANGELOG.md, components/composer/src/Composer.svelte
https://user-images.githubusercontent.com/34139730/144920586-fe22ec93-3f1b-429a-91b9-93a2bf43790f.mov
=> [composer] fix collapsible height and show_from prop

commons/src/types/ContactsSearch.ts, components/composer/CHANGELOG.md, components/composer/src/Composer.svelte, components/composer/src/components/ContactsSearch.svelte, components/composer/src/components/HTMLEditor.svelte, components/composer/src/index.html, components/composer/src/init.spec.js, components/composer/src/lib/store.ts, components/mailbox/src/init.spec.js, components/schedule-editor/src/init.spec.js, cypress/fixtures/composer/account.json, cypress/fixtures/composer/manifest.json, cypress/fixtures/users.json, cypress/support/commands.js, package.json, tsconfig.json, yarn.lock
https://user-images.githubusercontent.com/34139730/145051692-00888609-bec9-4858-9a94-d2c527d662b8.mov
=> [composer] fix show_bcc and show_cc buttons

lerna.json
=> [devops] ignore tests for release changes

components/agenda/CHANGELOG.md, components/composer/CHANGELOG.md, components/email/CHANGELOG.md, components/mailbox/CHANGELOG.md
=> [changelog] agenda v1.1.4, composer v1.1.4, email v1.1.4, mailbox v1.1.4

commons/src/components/Tooltip.svelte, components/email/CHANGELOG.md, components/email/src/Email.svelte
Mailbox component poorly displays emails [sc-74971]
- [email] show snippet when message body is empty
- [tooltip] fix issue causing muplitiple tooltips to open
- [tooltip] add support for text with icon
- [tooltip] add for html content
- [email] more readable participants list
- Before https://www.loom.com/share/28e83b454deb44d09851382cbd442264
-  After https://www.loom.com/share/1ab2fc41ea0f4ce28100f9cce78c51a1
- [] Added changes to component `CHANGELOG.md`
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this …
=> [mailbox] fix display issues with long list of participants in email

DOCUMENTATION.md, README.md, components/contact-list/src/ContactList.svelte, pull_request_template.md
=> Light documentation to offload Components knowledge

commons/src/methods/component.ts, components/availability/src/Availability.svelte, components/availability/src/init.spec.js, components/availability/src/method/availabilityUtils.ts, package.json, yarn.lock
- Refactor generateDaySlots function in Availability components and extract it for import
- Extract overlap and arrayContainsArray functions
=> Refactor and extract generateDaySlots function in Availability components

commons/src/store/events.ts, components/agenda/CHANGELOG.md, components/agenda/src/Agenda.svelte
=> [agenda] show no event message when no events"

components/availability/src/init.spec.js, cypress/support/commands.js
- Added a new method to Cypress commands to change the component id before each test runs
=> Fix flaky tests in Availability component

components/composer/src/Composer.svelte, components/composer/src/init.spec.js
- Cherry picked Aaron's commit for fixing Composer regression bug with attach button
- [X ] Cypress tests passing?
=> [Composer]: Fixing a change to the composer attach button that caused it to not work anymore

components/composer/CHANGELOG.md, components/email/CHANGELOG.md, components/mailbox/CHANGELOG.md
- Updated changelog release version
=> [Changelog]: Stable release for Email, Mailbox, Composer & Availability

components/mailbox/src/index.html
* composer using wrong id,  use "demo-composer"
=> [mailbox]fix mailbox demo can not send emails

commons/src/types/Nylas.ts, components/composer/CHANGELOG.md, components/composer/src/Composer.svelte, components/composer/src/properties.json, components/mailbox/src/index.html
- Added a prop r eset_after_close which resets after closing
=> [Composer]: Added a prop 'reset_after_close' which resets after closing

components/agenda/src/Agenda.svelte, tests/agenda/agenda.spec.ts, tests/mocks/MockManifests.ts
=> waiting for the most recent request to finish then returning the active query in the store

components/composer/src/cypress.html, components/composer/src/init.spec.js, cypress/support/index.js
=> [composer] fix flaky tests in GHA

components/availability/src/init.spec.js
- Refactored availability tests to only test one assertion
=> [availability] refactor tests to have single assertions

components/email/src/Email.svelte
- Wraps every message data in if show_receieved_timestamp
=> [email] respect show_receieved_timestamp in all cases

components/email/src/Email.svelte
- Displays reply buttons when passing data as properties
=> [email] ensure reply buttons available when passing properties

components/conversation/src/cypress.html, components/conversation/src/init.spec.js, cypress/fixtures/conversation/account.json, cypress/fixtures/conversation/manifest.json, cypress/fixtures/conversation/threadsId.json
=> [conversation] fix flaky tests

components/email/CHANGELOG.md, components/email/src/Email.svelte, components/email/src/methods/participants.ts
https://user-images.githubusercontent.com/34139730/149007130-1fd66f6f-1b31-4f69-bbcd-6c0deaa6aa3d.mov
=> [email] show cc participants when replying to all

commons/src/enums/Nylas.ts, components/email/src/Email.svelte, components/email/src/init.spec.js, components/mailbox/src/Mailbox.svelte, components/mailbox/src/index.html, components/mailbox/src/init.spec.js, cypress/fixtures/draftThread.json
- Added logic to mailbox component that opens composer when draft message is clicked
=> [mailbox] clicking on a draft email should open composer

components/scheduler/src/index.html
- remove unused events property
=> [scheduler] remove unused events property

components/agenda/src/cypress.html, components/agenda/src/init.spec.js, cypress/fixtures/agenda/calendars/calendarId.json, cypress/fixtures/agenda/events.json, cypress/fixtures/agenda/manifest.json
=> [agenda] add fixtures and intercepts to tests

commons/src/components/MessageBody.svelte, components/email/src/Email.svelte
- Removed await on `attachedFiles`
=> [Mailbox]: Potential fix for listing attachments not being shown in individual thread issue

components/email/src/Email.svelte
=> Added a test class to check what is going on with our publishing comamnd

.github/workflows/build-test-publish.yaml, commons/src/components/MessageBody.svelte, components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte
Removing our test ids and classes and testing publish without a cache build
=> Removing our test ids and classes and testing publish without a cache build

components/email/src/Email.svelte
=> Testing the email component publish build

.github/workflows/build-test-publish.yaml, components/email/src/Email.svelte, package.json
=> Moving from npm to yarn

.github/workflows/build-test-publish.yaml, components/email/src/Email.svelte
=> Fixed npm registery url

commons/src/components/MessageBody.svelte, components/agenda/src/Agenda.svelte, components/availability/src/Availability.svelte, components/composer/src/Composer.svelte, components/contact-list/src/ContactList.svelte, components/conversation/src/Conversation.svelte, components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte, components/schedule-editor/src/ScheduleEditor.svelte, components/scheduler/src/Scheduler.svelte
- Re-assignment for `attahcedFiles`
- Added new line to trigger release for all components
=> [MessageBody]: re-assign attachedFiled so the files are re-rendered

components/agenda/src/Agenda.svelte
- Removed unused/incorrect import (this is blocking Renegade)
=> [Agenda]: Removed unused/incorrect import

components/agenda/CHANGELOG.md, components/agenda/src/Agenda.svelte
=> [agenda] add min height to body of agenda

commons/src/connections/contacts.ts, commons/src/methods/api.ts, commons/src/store/contacts.ts, commons/src/types/Contacts.ts, commons/src/types/Nylas.ts, components/contact-list/CHANGELOG.md, components/contact-list/src/ContactList.svelte, components/contact-list/src/init.spec.js, components/contact-list/src/properties.json
=> [contact-list] support group prop

commons/src/methods/api.ts
- Detects error response object from API
Nothing has changed expect displaying a more descriptive error message. 
Improving the experience requires significant changes to the component.
Refactor happening during MVP push.
=> detect respone error messages from api

components/email/src/init.spec.js, components/email/src/methods/participants.ts
- modify single sender message cc field for new canReplyAll check
- adds default return value when you.email doesnt exist
=> fix email tests

components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte, components/mailbox/src/init.spec.js
- Accidentally overwrote the fix for delay when email is opened to view, bringing the code back.
=> Fixed issue where thread expanded in the mailbox component

commons/src/methods/isFileAnAttachment.ts, commons/src/types/Composer.ts, components/composer/src/Composer.svelte, components/email/src/Email.svelte, components/mailbox/CHANGELOG.md, components/mailbox/src/Mailbox.svelte, components/mailbox/src/index.html
- Attachments now appear in reply and draft messages
=> [composer]Attached files show up as attachments in draft emails and when replying to emails

components/composer/src/components/HTMLEditor.svelte, components/schedule-editor/src/init.spec.js
- Rolled back the change that added a css wrapper around the mail body in HTMLEditor
=> [composer]: roll-back css wrapper for last message in the mail body

components/schedule-editor/src/init.spec.js
=> [Hotfix, Schedule Editor, test] basic details class no longer a parent container, so tests need fixup

components/agenda/src/Agenda.svelte, components/composer/src/Composer.svelte, components/email/src/Email.svelte, components/mailbox/src/Mailbox.svelte
PR to bump our component versions. Right now this seems like the most straightforward way.
=> bumping the version for components

package.json
- Fix lerna publishing new packages to npm
=> public publish

components/agenda/src/Agenda.svelte, components/agenda/src/index.html, components/agenda/src/init.spec.js
- Modified the `StoredAllDayEvents` reactive variable to allow for passed  data
- Added a simple test case to account for passed data, both all-day and timespan based
- Side-effect: added a demo font family
=> [Agenda] All-Day Event is not loading from external data

commons/src/types/Nylas.ts, components/agenda/src/Agenda.svelte, components/agenda/src/init.spec.js
Adds [Event Metadata](https://developer.nylas.com/docs/developer-tools/api/metadata/) to descriptions in agenda events
=> [Agenda] Metadata as list in event description

components/theming/animation.scss
- adds z-index to progress-bar animation mixing
- 
=> fix progress-bar not visiable in availability list view

components/mailbox/src/Mailbox.svelte, components/mailbox/src/init.spec.js, cypress/fixtures/draftThread.json
=> Fix issue delete draft thread not updating

components/mailbox/src/Mailbox.svelte
=> Removed an unused import in mailbox

components/conversation/CHANGELOG.md, components/conversation/src/Conversation.svelte
=> Remove `sent by nylas` text from conversation body

commons/src/store/conversations.ts, components/conversation/src/Conversation.svelte, components/conversation/src/init.spec.js, cypress/fixtures/conversation/sendMessageResponse.json, cypress/fixtures/conversation/testConversationThread.json
=> Fix conversation not populate sent message to view

commons/src/methods/isFileAnAttachment.ts, components/email/CHANGELOG.md, components/email/src/init.spec.js, cypress/fixtures/email/messages/messageWithImageAttachment.json, cypress/fixtures/email/threads/threadWithImageAttachment.json
=> Optimized the logic of differentiating attachment files

components/mailbox/src/Mailbox.svelte
=> Fix mailbox type warning in code

commons/src/components/MessageBody.svelte, commons/src/methods/isFileAnAttachment.ts, components/composer/src/Composer.svelte, components/email/src/Email.svelte
=> Remove message variable from attachment check

components/composer/src/cypress.html, components/composer/src/index.html, components/composer/src/init.spec.js, components/contact-list/src/init.spec.js, components/conversation/src/init.spec.js, components/email/src/init.spec.js, components/mailbox/src/init.spec.js
=> Fixed Components cypress tests

commons/src/types/Nylas.ts, components/composer/CHANGELOG.md, components/composer/src/Composer.svelte, components/composer/src/init.spec.js, components/composer/src/lib/store.ts, tests/composer/lib/store.spec.ts
=> Fix the issue of can't having multiple Composers

commons/src/components/checkbox.scss, commons/src/types/Nylas.ts, components/email/src/Email.svelte, components/email/themes/auto.css, components/email/themes/dark.css, components/email/themes/light.css, components/mailbox/CHANGELOG.md, components/mailbox/src/Mailbox.svelte, components/mailbox/src/components/PaginationNav.svelte, components/mailbox/src/index.html, components/mailbox/src/properties.json, components/mailbox/themes/auto.css, components/mailbox/themes/dark.css, components/mailbox/themes/light.css, components/theming/variables.scss
https://user-images.githubusercontent.com/14408339/186533028-2c2a38c4-c8ca-4c99-a846-64c138c176e0.mov
=> Added custom CSS for Email and Mailbox components

components/composer/src/components/HTMLEditor.svelte, components/composer/src/init.spec.js
=>  and stop propagation for the composer toolbar events

components/booking/src/init.spec.js, components/schedule-editor/src/init.spec.js
=> Disabled some old tests for scheduler-editor and booking

components/agenda/CHANGELOG.md, components/agenda/src/index.html, components/agenda/src/styles/agenda-themes.scss
https://user-images.githubusercontent.com/14408339/193934100-59c3b358-dd11-4d33-9e86-871558d5435a.mov
=> Added event hover variable for Agenda component
